
environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
      - CONFIGURATION: Debug
        PLATFORM: x64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
    - cmake --build .

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\build
    - ctest .

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false
